"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const friend_graphics__genders_1 = require("./tables/friend_graphics__genders");
const friend_graphics__ages_1 = require("./tables/friend_graphics__ages");
const friend_graphics__apptypes_1 = require("./tables/friend_graphics__apptypes");
const friend_graphics__subscriptions_1 = require("./tables/friend_graphics__subscriptions");
const messages_statistic_1 = require("./tables/messages_statistic");
const friend_graphics__areas_jp_1 = require("./tables/friend_graphics__areas_jp");
const friend_graphics__areas_tw_1 = require("./tables/friend_graphics__areas_tw");
const friend_graphics__areas_th_1 = require("./tables/friend_graphics__areas_th");
const friend_graphics__areas_id_1 = require("./tables/friend_graphics__areas_id");
friend_graphics__genders_1.TableFriendGraphicsGenders.up();
friend_graphics__ages_1.TableFriendGraphicsAges.up();
friend_graphics__apptypes_1.TableFriendGraphicsApptypes.up();
friend_graphics__subscriptions_1.TableFriendGraphicsSubscriptions.up();
messages_statistic_1.TableMessagesStatistic.up();
friend_graphics__areas_jp_1.TableFriendGraphicsAreaJP.up();
friend_graphics__areas_tw_1.TableFriendGraphicsAreaTW.up();
friend_graphics__areas_th_1.TableFriendGraphicsAreaTH.up();
friend_graphics__areas_id_1.TableFriendGraphicsAreaID.up();
