"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const channel_controller_1 = require("../controllers/channel_controller");
let router = express_1.Router();
exports.router = router;
let channelController = new channel_controller_1.ChannelController();
router.get('/', channelController.index);
router.post('/account/add', channelController.addAccount);
router.get('/account/delete/:id', channelController.deleteAccount);
router.post('/group/add', channelController.createGroup);
router.get('/group/delete/:id', channelController.deleteGroup);
router.get('/group/export', channelController.exportDataInGroup);
router.get('/group/detail/:id', channelController.groupDetail);
