"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express = require("express");
const index_controller_1 = require("../controllers/index_controller");
let router = express.Router();
exports.router = router;
require('dotenv').config();
router.get('/', index_controller_1.IndexController.index);
router.get('/linedata/downcsv/:data', index_controller_1.IndexController.downCsv);
